### ISSUE TITLE
tiles-maven-plugin does not work under Maven 4

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#157]
It looks like looking up `ArtifactRepositoryLayout`'s under Maven 4 fails.

The code used to [lookup the layout by name](https://github.com/repaint-io/maven-tiles/blob/e5bedd523c0a6aa877e1a576677da8314eca6e34/src/main/groovy/io/repaint/maven/tiles/TilesMavenLifecycleParticipant.groovy#L311) is:

```java
repositoryLayouts = mavenSession.lookupMap(ArtifactRepositoryLayout.class.getName()) as Map<String, ArtifactRepositoryLayout>
```

and is used to [dynamically lookup the distribution repository layout](https://github.com/repaint-io/maven-tiles/blob/e5bedd523c0a6aa877e1a576677da8314eca6e34/src/main/groovy/io/repaint/maven/tiles/TilesMavenLifecycleParticipant.groovy#L368) when constructing a new `MavenArtifactRepository` instance to inject.

This is now deprecated, but nothing in the Maven source mentions what should be done instead of using it. 

```
[ERROR] Internal error: java.lang.NullPointerException: Cannot invoke "org.codehaus.plexus.PlexusContainer.lookupMap(String)" because "this.container" is null -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException: Cannot invoke "org.codehaus.plexus.PlexusContainer.lookupMap(String)" because "this.container" is null
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:157)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:981)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:291)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:208)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
Caused by: java.lang.NullPointerException: Cannot invoke "org.codehaus.plexus.PlexusContainer.lookupMap(String)" because "this.container" is null
    at org.apache.maven.execution.MavenSession.lookupMap(MavenSession.java:486)
    at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRead(TilesMavenLifecycleParticipant.groovy:311)
    at org.apache.maven.DefaultMaven.callListeners(DefaultMaven.java:377)
    at org.apache.maven.DefaultMaven.afterProjectsRead(DefaultMaven.java:359)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:269)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:225)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:149)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:981)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:291)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:208)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.lang.reflect.Method.invoke(Method.java:580)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
```

@cstamas What's the best approach to handle this, so it'll work under Maven 3.9.9 and 4.0.0-beta4?

**Comment by cstamas** [comment]
All these classes _are deprecated_ in Maven 3.9.x:
https://github.com/apache/maven/blob/maven-3.9.x/maven-artifact/src/main/java/org/apache/maven/artifact/repository/layout/ArtifactRepositoryLayout.java#L29
https://github.com/apache/maven/blob/maven-3.9.x/maven-artifact/src/main/java/org/apache/maven/artifact/repository/ArtifactRepository.java#L32

Migration off these classes and use of Resolver instead warmly recommended.

**Comment by cstamas** [comment]
Moreover, all the lookup is deprecated as well (way way before Maven 3.9, since Maven 3.3.x?):
https://github.com/apache/maven/blob/maven-3.9.x/maven-core/src/main/java/org/apache/maven/execution/MavenSession.java#L388-L411

**Comment by jimisola** [comment]
@talios That's what I suspected. We're probably not able to be first out of the gate with 4.0.0 anyway as I expect that we use some plugins that won't work directly.

That said, I'd like to thank you for your work with Maven Tiles - it's been a game changer for our team.
