### ISSUE TITLE
Exception running tiles plugin v2.2

### ISSUE THREAD

**Issue by Tzrlk** [repaint-io/maven-tiles#27]
```
[INFO] Scanning for projects...
---------------------------------------------------
constituent[0]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar
constituent[1]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar
constituent[2]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar
constituent[3]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar
constituent[4]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar
constituent[5]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar
constituent[6]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/commons-io-2.2.jar
constituent[7]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar
constituent[8]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar
constituent[9]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar
constituent[10]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar
constituent[11]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar
constituent[12]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar
constituent[13]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar
constituent[14]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar
constituent[15]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar
constituent[16]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar
constituent[17]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar
constituent[18]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar
constituent[19]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar
constituent[20]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar
constituent[21]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar
constituent[22]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar
constituent[23]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar
constituent[24]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar
constituent[25]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar
constituent[26]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar
constituent[27]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar
constituent[28]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/wagon-file-2.8.jar
constituent[29]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar
constituent[30]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar
constituent[31]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2014.1.4/plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getAllProjects()Ljava/util/List;
	at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRead(TilesMavenLifecycleParticipant.groovy:223)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by talios** [comment]
Doh - looks like we've walking into more APIs that are only available in the newer Maven releases.  I can see this exception is coming from IntelliJ ( and quite possibly intellij is configured to use the older/embedded maven version they ship with ).

Might pay to now officially drop the old version, but also add an explicit version check with a more suitable error message.

**Comment by Tzrlk** [comment]
Yep, that was it.

**Comment by talios** [comment]
Why

**Comment by talios** [comment]
Why close? Keep it up for the improved messages.

**Comment by rvowles** [comment]
Closed because we don't use it.

**Comment by talios** [comment]
Closed now because we also no longer use the getAllProjects method
