### ISSUE TITLE
java.lang.IllegalAccessError: org/apache/maven/project/DefaultModelBuildingListener 

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#41]
IntelliJ 15 seems to trigger with this error _occasionally_ on one of our projects when configured to use the upcoming Maven 3.3.8 release, tho I've seen it on a few earlier releases.

Even tho IntelliJ is configured to use the external Maven release, the stacktrace points to using the internal Maven30Server still...

    2015-11-09 10:51:09,594 [ 138592]   INFO -      #org.jetbrains.idea.maven - org/apache/maven/project/DefaultModelBuildingListener 
    java.lang.IllegalAccessError: org/apache/maven/project/DefaultModelBuildingListener
      at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.thunkModelBuilder(TilesMavenLifecycleParticipant.groovy:287)
      at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.orchestrateMerge(TilesMavenLifecycleParticipant.groovy:268)
      at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRead(TilesMavenLifecycleParticipant.groovy:245)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl.loadExtensions(Maven30ServerEmbedderImpl.java:737)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl.access$300(Maven30ServerEmbedderImpl.java:104)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl$2.run(Maven30ServerEmbedderImpl.java:621)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl.executeWithMavenSession(Maven30ServerEmbedderImpl.java:568)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl.doResolveProject(Maven30ServerEmbedderImpl.java:586)
      at org.jetbrains.idea.maven.server.Maven30ServerEmbedderImpl.resolveProject(Maven30ServerEmbedderImpl.java:532)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
      at sun.rmi.transport.Transport$1.run(Transport.java:200)
      at sun.rmi.transport.Transport$1.run(Transport.java:197)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
      at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
      at java.security.AccessController.doPrivileged(Native Method)
      at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
      at java.lang.Thread.run(Thread.java:745)
    2015-11-09 10:51:09,625 [ 138623]   INFO -      #org.jetbrains.idea.maven - [WARNING] tiles-maven-plugin in project smx3:smx3.templates:14.1.121-SNAPSHOT requested for same tile dependency com.smxemail.tiles:com.smxemail.tiles.release:[2.0.0,3.0.0)

**Comment by rvowles** [comment]
I've seen this against Maven 3.2.x

**Comment by rvowles** [comment]
Swapped back to Maven 3.2.5 to confirm this error, fixed it in upcoming 2.6
