### ISSUE TITLE
IntelliJ IDEA 15.0.4 mvn install results in missing ModelBuilder2 injection

### ISSUE THREAD

**Issue by Tzrlk** [repaint-io/maven-tiles#58]
2.4 through to 2.7 (inclusive) work fine. The only version affected is 2.8.

```
Mar 17, 2016 1:22:35 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: io.repaint.maven.tiles.TilesMavenLifecycleParticipant
java.lang.NoClassDefFoundError: org/apache/maven/model/building/ModelSource2
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getDeclaredConstructors(Class.java:2012)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:98)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:831)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:758)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:255)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:204)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:954)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1018)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.model.building.ModelSource2
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 56 more

---------------------------------------------------
constituent[0]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar
constituent[1]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar
constituent[2]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar
constituent[3]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar
constituent[4]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar
constituent[5]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar
constituent[6]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/commons-io-2.2.jar
constituent[7]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar
constituent[8]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar
constituent[9]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar
constituent[10]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar
constituent[11]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar
constituent[12]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar
constituent[13]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar
constituent[14]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar
constituent[15]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar
constituent[16]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar
constituent[17]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar
constituent[18]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar
constituent[19]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar
constituent[20]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar
constituent[21]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar
constituent[22]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar
constituent[23]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar
constituent[24]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar
constituent[25]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar
constituent[26]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar
constituent[27]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar
constituent[28]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/wagon-file-2.8.jar
constituent[29]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar
constituent[30]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar
constituent[31]: file:/C:/Program%20Files%20(x86)/JetBrains/IntelliJ%20IDEA%2015.0.3/plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/maven/model/building/ModelSource2
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getDeclaredConstructors(Class.java:2012)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:98)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:629)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:831)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:758)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:255)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:204)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:954)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1018)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.apache.maven.model.building.ModelSource2
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 56 more
```

**Comment by rvowles** [comment]
Are you using the built in Maven (unsupported) or an external 3.3+ one? (supported)

**Comment by Tzrlk** [comment]
Ah, good spot, I was using both the internal maven, and my external one was only 3.2.3.

Are the 3.3.x maven releases actually usable now?

**Comment by talios** [comment]
They always were - at least the _actual_ released ones.
