### ISSUE TITLE
Update or reference example

### ISSUE THREAD

**Issue by paulvi** [repaint-io/maven-tiles#62]
Update or reference example.
Where are example project to compile with the latest 2.8 version?

While trying to `mvn packge` over https://github.com/maoo/maven-tiles-examples

using 2.8 in

```
<build>
    <plugins>
      <plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <version>${maventiles.plugin.version}</version>
        <extensions>true</extensions>
      </plugin>
    </plugins>
  </build>
```

I got

```
D:\Workspaces\GitHub\maven-tiles-examples>mvn -e
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] Usage of maven-tiles prohibited from multi-module builds where reactor is used as parent. -> [Help 1]
org.apache.maven.MavenExecutionException: Usage of maven-tiles prohibited from multi-module builds where reactor is used as parent.
        at io.repaint.maven.tiles.TilesMavenLifecycleParticipant.afterProjectsRead(TilesMavenLifecycleParticipant.groovy:281)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by rvowles** [comment]
Your tiles plugin definitions are in the children rather than the parent right?

**Comment by paulvi** [comment]
Richard, that is just the only GitHub example I found at https://github.com/maoo/maven-tiles-examples

This issue is not about to make it pass, but to have an example to point from README 

@talios

**Comment by rbygrave** [comment]
FYI: If people are looking for more examples there are some in:
https://github.com/avaje-pom
tile-runnable-jar
tile-pygments-doclet
tile-dependency-tree
tile-kotlin-compile
tile-java-compile
tile-ebean-enhancement

I think it would be good for the documentation to reference more recent of
examples (the maoo examples are 4 years old and not in the correct format
now etc).

**Comment by rvowles** [comment]
@paulvi - that project is nothing to do with this project (apart from the genesis idea), which is possibly why you are having trouble :-(

@talios also has some examples, but thanks @rbygrave !

**Comment by talios** [comment]
@rbygrave I look forward to a documentation Gerrit Review in your future :)

**Comment by rbygrave** [comment]
I'll add it to the list. Probably get to it around .... 2018 :)

**Comment by rbygrave** [comment]
Er, that was a cheeky comment from me. 

On a more serious note I'd rate tiles as massively important ... And to me the documentation does need some attention. So I'll take this offline (do you want a full website etc).

Of hand I'd say ... People generally know less than you think and more explanation of why tiles exists might be good.

**Comment by talios** [comment]
@rbygrave Mine was equally as cheeky as well. Thankfully we know each other. Documentation is always one of the hardest things in software I think.

**Comment by paulvi** [comment]
as for me, I am looking for showcase example. That would also be test suit for all tiles features.

**Comment by mnisius** [comment]
Hi, 
I just found out of this plugin exists. The idea is gread but I have no idea how to use it. 

It would help a lot if you could provide a simple example with maybe 2 or 3 tiles used in an simple Hello World application.
